name: flutter_web_app
description: A new Flutter web application.

publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/  # Add your asset files here if needed.